### ISSUE TITLE
Add multi-selection for ListView

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#122]
ListView widget still does not have multi-selection. Multi-selection can be useful in various situations and should be implemented.

**Comment by gbutler69** [comment]
I can give this one a try.

**Comment by gbutler69** [comment]
@mrDIMAS: I would imagine you'd want this to work as follows:

  1. Click on Item - Select if not selected and unselect all other items
  2. CTRL-Click on Item - Add to Selection if not selected; Unselect if selected - in either case don't change other selections
  3. SHIFT-Click on Item - Select all items between the previously clicked selection and the current item (including the current item clicked)

Is this the intended behavior?

Next, I notice that the Mouse messages do not include the state of the modifier keys (CTRL, SHIFT, ALT, SUPER, etc). Should those messages include that information? Where would be best to look at that?

**Comment by mrDIMAS** [comment]
You absolutely right, this is exactly how it should behave.

To get the state of modifiers, use the `ui.keyboard_modifiers()`

**Comment by gbutler69** [comment]
@mrDIMAS : Isn't the fact that the modifier key state is not in the event going to result in timing issues when checking the ```ui.keyboard_modifiers()```. Would it be better to build infrastructure to put the modifiers in the event first?

**Comment by mrDIMAS** [comment]
I think all you can do is to put a copy of `keyboard_modifiers` field of `UserInterface` struct in an event, but this won't help much, because timing issues are somewhat impossible with current implementation. Also, rg3d uses winit for windowing, and it does not provide the state of keyboard modifiers as part of key pressed/released events, instead it has separate event specifically for modifiers.
