### ISSUE TITLE
Support more KeyCodes

### ISSUE THREAD

**Issue by Eragonfr** [FyroxEngine/Fyrox#151]
Some computers have unsupported keys like `é`, `è` or `ù`
And they are directly accessible on the keyboard without any key combination.
I only can think of AZERTY and BÉPO with them, but I'm sure that if we search a little bit more we can find many more keyboard layout with other key accessible.

It could be a good idea to change the way the key is handled so you won't need an Enum with every key in the world.

**Comment by mrDIMAS** [comment]
rg3d uses winit to handle input, and winit use VirtualKeyCode to define a fixed set of keys on various keyboards. It means that VirtualKeyCode is mapped **directly** on a physical key on your keyboard. However for some situations it is not enough, and to solve this every OS provides a set of mappings from physical keys to a character set. For example QWERTY is (mostly) 1-to-1 mapping from physical to character set, but AZERTY is a different mapping. To handle this, winit provides a special event called `WindowEvent::ReceivedCharacter` which has **mapped** unicode character.

**Comment by mrDIMAS** [comment]
I added a `Scancode` enum (see the commit above), it could be used to get the state of a physical key, that does not depend on the keyboard layout of your OS.
