### ISSUE TITLE
Can't start simple example on Ubuntu Touch

### ISSUE THREAD

**Issue by jonnius** [FyroxEngine/Fyrox#163]
Hi there. I was curious to see whether this engine runs on Ubuntu Touch (based on Ubuntu 16.04) on the Pinephone (Wayland Compositor). When I try to start the `simple` example, I get:
```
'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed'
```
If I provide it with the socket via env var `WAYLAND_SOCKET=/run/user/32011/wayland-0` I run into:
```
'Failed to initialize any backend! Wayland status: InvalidFd X11 status: XOpenDisplayFailed'
```
`/run/user/32011/wayland-0` exists and is a valid Wayland socket.

Does this engine support EGL? Do you have any idea what could be wrong here?

**Comment by mrDIMAS** [comment]
The engine uses OpenGL 3.3 Core on desktop systems and OpenGL ES 3.0 on WebAssembly. Your device seem to support OpenGL ES 3.0, but not OpenGL 3.3.

**Comment by mrDIMAS** [comment]
I did experimental change, please check again if it works for you.

**Comment by jonnius** [comment]
Hi there. Thanks for your response. I just tried again, still getting the same error message ([backtrace](https://pastebin.com/fEPRsRiC)).

Note: I just edited the first error message in the original post.

**Comment by mrDIMAS** [comment]
Closing this because it is a hardware issue, the device does not meet minimal requirements (OpenGL 3.3+).
