### ISSUE TITLE
Window doesnt fill the screen

### ISSUE THREAD

**Issue by tekakutli** [FyroxEngine/Fyrox#167]
hello there, I am using sway(wayland) in arch(linux) and I encountered some issues

the window doesn't fill the screen space 
https://a.uguu.se/lrUKdnKe.png
if I move it to a workspace of its own it keeps the same size(see next image), same if I full-screen it (then: the empty space becomes  black)
this is an issue because I cant see the top menu
the mouse is also offset, the red dot indicates the distance where the mouse actually clicks

here in a workspace of its own:
https://a.uguu.se/DaaavkVM.png
in a red box you can see a completely unrelated issue: when you scroll the assets those grey boxes vibrate into existence

thank you anyway

**Comment by DuckEater54** [comment]
Your image links are expired. Use a website like Imgur.

**Comment by tekakutli** [comment]
> @tekakutli could you please confirm if @w-flo 's change has fixed the issue for you, and if so, close the issue?

indeed, thank you @w-flo
