### ISSUE TITLE
Improve documentation, add more code examples.

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#172]
1) Lots of structures now have `See module docs.` as the docs, and the actual docs located in the module documentation. This should be reversed. 
2) Lots of places in the docs could have code examples.
3) Some places still lacks good "potential usage" examples.

**Comment by Dennis-Zhang-SH** [comment]
Hi, if you don't mind, I can help you with the documentation.

**Comment by mrDIMAS** [comment]
Thanks! I really appreciate this. Could you please post here on what you'll be working, just to ensure that the only one person works on a thing.

**Comment by Dennis-Zhang-SH** [comment]
I just found your repo today, and I decide to make a simple 2D game by using it, so I think I can start with 2D stuff.

**Comment by DuckEater54** [comment]
If you don't mind, I can write a book for the rg3d.rs using mdBook. More for tutorials but also as an Fyroxinomicon.

**Comment by mrDIMAS** [comment]
Sounds cool! Yeah, Fyrox will be the name.
