### ISSUE TITLE
Feature flags for 2d and 3d

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#194]
I think putting big deps like `rapier2d` behind a `2d` feature flag could improve compile times for games which don't need it. Correct me if i am wrong but i don't think most 3d games normally require rapier2d, yet it's functions end up in the generated binary. Conversely, i don't think most 3d-specific stuff is necessary for 2d games so a `3d` feature could improve their compile times.

**Comment by mrDIMAS** [comment]
Right, that is indeed a must-have feature. Also, since 2d and 3d are completely isolated (they even use different renderers), it could be done pretty easily.
