### ISSUE TITLE
Scrollbar has fixed size and sometimes is so big that it can't be dragged.

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#199]
In the screenshot you can see 4 entries but there are actually 6. The widget is however so small that dragging the scrollbar with mouse is impossible - i have to click the down arrow (or... thinking about it now... use the mouse wheel but mine is broken so it didn't occur me until now ;) ).

The underlying issue is that the scrollbar has a fixed size but increasing the side of this widget would be a nice thing too.

![2021-10-08-182944_418x282_scrot](https://user-images.githubusercontent.com/4079823/136591684-5156e154-5c45-40ca-bbc9-6ee3edfa1a60.png)

**Comment by shyamjayakannan** [comment]
@mrDIMAS will decreasing the minimum size here help?

https://github.com/FyroxEngine/Fyrox/blob/7de5a3107da2dfab180fd23f4c79b2542b466d70/fyrox-ui/src/scroll_bar.rs#L548-L555

**Comment by mrDIMAS** [comment]
I think the size of the `indicator` should be adaptive to the actual size of the content of a `ScrollViewer`. This issue is a bit more complex than just decreasing the size, simply because currently the size is fixed and decreasing it would result in quite unusable scroll bar.
