### ISSUE TITLE
Add cascaded shadow maps for directional light sources

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#220]
Directional lights still lacks proper shadows support, a relatively easy way to add shadow mapping for them is to implement cascaded shadow maps (CSM) technique.

**Comment by w-flo** [comment]
About that
```
            // TODO: For some reason this coefficient is crucial, without it CSM bugs when cascades
            // don't overlap for some frustum orientations. Investigate why this is needed.
            const CASCADE_Z_OVERLAP: f32 = 10.0;
```
thing: I've noticed that there is some weird Z axis flip that leads to the following vector having a Z component that is far outside of the expected [0,1] range: `light_view_projection.transform_point(&Point3::from(frustum.right_bottom_front_corner())).coords` This would have values like 25 for the Z component depending on my frustum orientation etc.

As I understand it, everything inside the frustum (and the frustum corners) should have coordinate components inside [0,1] after going through the light view and light projection transform, so there is something wrong there.

I figured out that this is fixed for my scene setup by doing:
```
diff --git a/src/renderer/shadow/csm.rs b/src/renderer/shadow/csm.rs
index 0f1ac52..9f97673 100644
--- a/src/renderer/shadow/csm.rs
+++ b/src/renderer/shadow/csm.rs
@@ -156,7 +156,7 @@ impl CsmRenderer {
             black_dummy,
         } = ctx;
 
-        let light_direction = -light
+        let light_direction = light
             .up_vector()
             .try_normalize(f32::EPSILON)
             .unwrap_or_else(Vector3::y);
@@ -201,17 +201,13 @@ impl CsmRenderer {
                 aabb.add_point(light_space_corner);
             }
 
-            // TODO: For some reason this coefficient is crucial, without it CSM bugs when cascades
-            // don't overlap for some frustum orientations. Investigate why this is needed.
-            const CASCADE_Z_OVERLAP: f32 = 10.0;
-
             let projection_matrix = Matrix4::new_orthographic(
                 aabb.min.x,
                 aabb.max.x,
                 aabb.min.y,
                 aabb.max.y,
-                aabb.min.z,
-                aabb.max.z + CASCADE_Z_OVERLAP,
+                -aabb.min.z,
+                -aabb.max.z,
             );
 ```

There is another issue where sometimes, off-screen objects that still need to cast shadows on screen fall outside of the near/far clipping planes of the orthographic light projection, so the shadow of that off-screen objects, or at least parts of it, disappear. I'm not sure what the best way to fix this is, I experimented by doing this:
```
                -aabb.min.z + (aabb.max.z - aabb.min.z).abs() * 0.5,
                -aabb.max.z - (aabb.max.z - aabb.min.z).abs() * 0.5,
```
and it seems to work in those cases that I noticed earlier, but I'm not sure if that's a great general solution (also that abs() call is pretty useless I guess).

**Comment by w-flo** [comment]
So I just wanted to add that my initial attempt of
```
                -aabb.min.z + (aabb.max.z - aabb.min.z).abs() * 0.5,
                -aabb.max.z - (aabb.max.z - aabb.min.z).abs() * 0.5,
```
is apparently not enough to always keep the shadow "alive" for a tall building in my scene when that building goes off-screen. I wonder what the commonly accepted solution to this problem is, maybe just "push in/out" the near/far plane of the light frustum even more? At which point will shadow acne become a problem though especially with HALF precision?

**Comment by mrDIMAS** [comment]
Yeah, this problem is annoying, [this article](https://developer.download.nvidia.com/SDK/10.5/opengl/src/cascaded_shadow_maps/doc/cascaded_shadow_maps.pdf) has a solution for that, it inflates bounding box in X and Y axes. It is worth to try 🤔
