### ISSUE TITLE
Headless (dedicated) mode for multiplayer game servers

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#222]
I am not completely sure what i really want here, i am still figuring things out but i'll create an issue now to share my findings, maybe other people have also tried writing multiplayer game servers and will chip in. I'll keep updating the issue as i have a clearer idea of what i want from rg3d and maybe we can come up with a decent API for it.

- There should be a way to use rg3d without creating a window. `Engine::new` expects a window builder and an event loop. The window builder is completely unnecessary and i *think* i'd prefer to write my own event loop as well since all it's gonna do is respond to network anyway. (Long term maybe also stdin/out for quick server config changes and filesysten changes for hot reloading.)
- Most of `Engine`'s fields are not necessary - only `resource_manager`, `scenes` and `scenes2d` are needed on a server.
- It would be nice to load only the scene graph and geometry from assets for collision detection. Textures are not necessary, not loading them could save memory.

---

- Not necessarily related but mentioning it here in case it affects API design: Multiplayer game clients should send (some kinds of) input to server immediately, not once per frame. That means blocking the main thread with winit's event loop as little as possible and doing all work on a separate thread. This is *probably* already achievable without changes to rg3d (by spawning a separate thread, passing input to it using channels, doing engine updates and rendering from that thread).

**Comment by martin-t** [comment]
I wanted a way to run my fyrox game on github's CI. This has 2 issues:
- There are no graphics
  - This can be solved on linux by using xvfb and installing some opengl libs (libegl1-mesa libegl1) and running inside xvfb: https://github.com/rustcycles/rustcycles/blob/3d701480c7574a5f645344282dd25babf65c79fb/.github/workflows/ci.yml#LL56C22-L56C22. 
  - Idk how to solve it on windows and mac.
- There is no audio. I couldn't find a way to get around that, the game would simply crash so i made a PR that offers an option to use a dummy audio device.

**Comment by mrDIMAS** [comment]
This is now possible to do by not calling `Engine::initialize_graphics_context` when using the engine in a "framework" mode (read - with custom game loop).
