### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#229]
So i know you see it as extra work but i think it's *essential* if you want rg3d to be seen as a mature and usable project and i am gonna keep bugging you until you add it ;)

- For people who are engine-shopping and keep checking rg3d out once every few months, it's a good way to judge progress.
- For people upgrading from previous versions of rg3d, it's indispensable for quickly fixing  breaking  changes. It's the first place i look when updating a dep in any of my projects.

Right now i am updating from 0.23 to latest master and i have to go through rg3d's git history to figure out what changed. Some things that would have been mentioned in CHANGELOG.md to make it easier:
    - A whole bunch of stuff like `Engine` is no longer generic, the type aliases can be removed, `StubNode` is gone.
    - The `physics` module split into `pyhsics2d` and `physics3d` with slightly different internal organization, `RigidBodyHandle` moved to `physics*d`.
    - `set_frame_size` moved from `Engine::renderer` to `Engine`
I'd make a PR with a tiny incomplete changelog and these changes in it but you know better what exactly changed.

**Comment by w-flo** [comment]
I'd also note the changed API for setting material properties (&ImmutableString for the property name instead of whatever it used to be before).

**Comment by mrDIMAS** [comment]
@martin-t Ok, you win 😃 . I'll start a change log.

**Comment by mrDIMAS** [comment]
Closing this, since I've already made change log for 0.24, I'll continue updating it.
