### ISSUE TITLE
Rename rg3d

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#239]
I decided to rename the engine two months ago, because rg3d was a working title from the beginning. I made a poll in [Discord server](https://discord.gg/xENF5Uh) and in [Discussions](https://github.com/rg3dengine/rg3d/discussions/103). Community has chosen **Fyrox** as the new name of the engine. 

The engine will be renamed before releasing its new version on crates.io. The Fyrox will have 0.24 version, because it is the same engine, but with different name. rusty-editor will also be renamed into **Fyroxed**.

The web site will have the old domain name for some time, I also renewed rg3d.rs domain name for one year. The new domain name will be purchased soon. The web site itself requires redesign. 

The new logo will also be created, there were some cool proposals on Discord server, most likely that I'll rework some of them or just draw one from scratch.

**Comment by DuckEater54** [comment]
Question: wouldn't this task be as simple as "Find and Replace"?

**Comment by mrDIMAS** [comment]
The renaming is almost done, there are some more steps:

- Migrate rg3d.rs -> fyrox.rs (redirect from rg3d.rs to fyrox.rs as well)
- Publish Fyrox on crates.io
- Fix links in the book
- Change rg3d -> Fyrox in the book

**Comment by Voodlaz** [comment]
@mrDIMAS GitHub supports checkboxes, they're good for what you need t do in that message

**Comment by mrDIMAS** [comment]
Migration is complete.
