### ISSUE TITLE
Implement automatic dynamic + static batching

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#248]
One step further has to be done to add full featured batching, the engine already has batcher, but it does not create a single vertex/index buffer for batch. Every object from batch will still be drawn one by one. This must be fixed to achieve better rendering performance, it is especially useful for situations with tons of objects with the same material.

**Comment by seivan** [comment]
Yeah, I noticed that 2D (Sprites) aren't batched. That's somewhat of a low hanging fruit, then again I am not familiar if it's because the engine needs to support 3D.

If they got the same texture & shaders, batching shouldn't be too tricky to add.

**Comment by mrDIMAS** [comment]
Rectangle is for 2D only and it supports batching, sprites are 3D only and not batched. The main difference is that sprites always facing towards the camera.

**Comment by mrDIMAS** [comment]
This is more or less done.
