### ISSUE TITLE
Type convert bug in 'UiNode::cast()'

### ISSUE THREAD

**Issue by WangHoi** [FyroxEngine/Fyrox#256]
Maybe there is a bug:
```rust
impl UiNode {
  pub fn cast<T: Control>(&self) -> Option<&T> {
      self.0.as_any().downcast_ref::<T>()
  }
}
```

To consider composition style inheritance, it should be
```rust
impl UiNode {
  pub fn cast<T: Control>(&self) -> Option<&T> {
      self.0
          .query_component(TypeId::of::<T>())
          .map(|a| a.downcast_ref::<T>())
          .flatten()
  }
}
```

**Comment by mrDIMAS** [comment]
Hi, `query_component` was added after `cast` and I just didn't think that `cast` could be improved in this way. This seems to be a very good improvement 🤔

**Comment by mrDIMAS** [comment]
I explained the difference of the methods in the docs - https://github.com/FyroxEngine/Fyrox/blob/master/fyrox-ui/src/node.rs#L90-L111
