### ISSUE TITLE
What is the current method for updating old .rgs files that no longer load?

### ISSUE THREAD

**Issue by slightlyoutofphase** [FyroxEngine/Fyrox#271]
It seems like there must be one, otherwise I don't understand how you would be able to keep updating StationIapetus, or any of the example programs, and so on.

**Comment by mrDIMAS** [comment]
Yeah, there is one - basically you need to install rusty-editor from crates.io and re-save all your scenes:

```shell
cargo install rusty-editor
rusty-editor
```

And then re-save scenes one-by-one. In newer versions of the engine backward compatibility was removed. I forgot to mention that in the change log and on the 0.24 announcement page.

**Comment by slightlyoutofphase** [comment]
Thanks!
