### ISSUE TITLE
Is the created game with Rust safe from manipulation by third-party software? (Cheater, Hacker, Anti-Cheat?)

### ISSUE THREAD

**Issue by TheRainbowSun** [FyroxEngine/Fyrox#276]
Is it possible to manipulate a published game programmed with Rust using third party software to gain advantages over others?
I ask myself this question because programming with Rust does not allow bugs in the code. There would be no need for an Anti-cheat system if the programming language itself prevents the cheater from doing it or does not allow it because of illegal added codes that he cannot interpret.

**Comment by mrDIMAS** [comment]
No, you still need anti-cheat system, which includes packets encryption, machine code obfuscation, and similar techniques. Rust only guarantees memory safety, it won't stop any machine code modifications in final binary, it won't magically solve any of your design flaws that can lead to abuse of game mechanics, and so on.

**Comment by TheRainbowSun** [comment]
This is a real pity. I wanted to release an open source online community game and thought I wouldn't need an extra anti-cheat system because of the Rust programming language. It would have been a win-win situation for everyone, so to speak. Encrypting the game with technical mechanics makes no sense in this scenario if it is open source anyway.

**Comment by ethindp** [comment]
Your not going to find any language in existence that will provide this. Cheaters will always, always find a way of cheating. No programming language can protect you from this.
