### ISSUE TITLE
[Research] Proc-macro for editor commands 

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#281]
Research a way of generating editor commands using a proc macro. Currently every command is written by hand, in most cases they're pretty small (https://github.com/FyroxEngine/Fyrox/blob/master/editor/src/scene/commands/light.rs#L11), but still it is a boilerplate code that can be generated. In the majority of cases, a command is just swapping two values in some object. Here is a simple example:

```rust
use crate::{Command, SceneContext};
use fyrox::core::pool::Handle;
use fyrox::scene::graph::Graph;
use fyrox::scene::node::Node;

#[derive(Debug)]
pub struct SetNodeNameCommand {
    handle: Handle<Node>,
    name: String,
}

impl SetNodeNameCommand {
    fn swap(&mut self, graph: &mut Graph) {
        let node = &mut graph[self.handle];
        let old = node.name_owned();
        node.set_name(self.name.clone());
        self.name = old;
    }
}

impl Command for SetNodeNameCommand {
    fn name(&mut self, context: &SceneContext) -> String {
        "Set Node Name".to_string()
    }

    fn execute(&mut self, context: &mut SceneContext) {
        self.swap(&mut context.scene.graph);
    }

    fn revert(&mut self, context: &mut SceneContext) {
        self.swap(&mut context.scene.graph);
    }
}
```

Lots of code to just swap two values, current approach to reduce amount of boilerplate code is to use macros:

```rust
define_node_command!(SetNameCommand("Set Name", String) where fn swap(self, node) {
    get_set_swap!(self, node, name_owned, set_name);
});
```
I think there should be a way to generate this code procedurally.

The macro should just cover simple cases like one above, because there are much more complex commands that can't be generated, because they're containing some complex logic (https://github.com/FyroxEngine/Fyrox/blob/master/editor/src/scene/commands/navmesh.rs#L53)

**Alternative:** Improve existing standard macros, to create commands in a single line, this solution is acceptable too.

**Comment by toyboot4e** [comment]
I'm considering such a declartive macro

```rust
define_swap_command! {
    |node| node.as_light_mut(),
    [
        SetLightScatterCommand("Set Light Scatter", f32, scatter, set_scatter),
        SetLightIntensityCommand("Set Light Intensity", f32, intensity, set_intensity),
    ],
    |node| node.as_light_mut().as_spot_mut(),
    [
        SetSpotLightHotspotCommand("Set Spot Light Hotswap", f32, scatter, set_scatter),
        SetLightIntensityCommand("Set Light Intensity", f32, intensity, set_intensity),
    ],
}
```

If we retrieve the human readable name with `std::any::type_name::<Self>()` and `convert_case` at runtime (maybe using `once_cell` cache or not), the name string can be removed:

```rust
define_swap_command! {
    |node| node.as_light_mut(),
    [
        SetLightScatterCommand(f32, scatter, set_scatter),
        SetLightIntensityCommand(f32, intensity, set_intensity),
    ],
    |node| node.as_light_mut().as_spot_mut(),
    [
        SetSpotLightHotspotCommand(f32, scatter, set_scatter),
        SetLightIntensityCommand(f32, intensity, set_intensity),
    ],
}
```

**Comment by mrDIMAS** [comment]
Yeah, I realized that proc macro is somewhat hard to add here. I like your approach, it is much more compact and there's less boilerplate.

**Comment by toyboot4e** [comment]
Then I would try polishing the existing macro.

Other options..

1. Using [paste](https://github.com/dtolnay/paste) crate to concatenate identifiers
  e.g. create `is_$xxx` and `set_$xxx` from `$xxx:ident`. But that wouldn't always work well, e.g. for `set_scatter_enabled` and `enable_scatter`.

2. Proc macro
  Maybe as you thoguht, it would not go further than `paste`.

3. Using traits
  It would not reduce boilerplate code than macros I guess.

**Comment by mrDIMAS** [comment]
Yeah, polishing existing macro is the right way.

**Comment by mrDIMAS** [comment]
I think that can be closed, since there are already some great improvements have been made.
