### ISSUE TITLE
Forward renderer broken

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#293]
I am pretty sure commit 4eb42cb0e1654f54b43a5c01b4ae45ec56931bd1 broke transparency by making everything use the deferred renderer.

This is 4eb42cb0e1654f54b43a5c01b4ae45ec56931bd1:
![Screenshot_20220208_144344](https://user-images.githubusercontent.com/4079823/152999283-8c4024c7-65c8-4daa-8f1d-c95195425165.png)

This is 14f652ecb5a7ba9f55809bc32671b6fecf0d804f:
![Screenshot_20220208_144414](https://user-images.githubusercontent.com/4079823/152999294-532a000d-30d9-42d3-8be6-2df48351be46.png)

I am aware multiple translarent layers are not supported but you can't see even the part of the wall that is behind only one transparent layer (I extended the wall below all 3 floor layers now to test this).

**Comment by martin-t** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/4079823/153020658-724a1aa1-b459-4c3c-9ad9-f7008eb01313.png)

(I used c24bfa5679161625c7edad07d7df93cb75979522 editor for the screenshot if that matters, but last time the scene was saved was ages ago)

Note that it appears some floors are there multiple times, i haven't gotten around to cleaning it up yet, but it doesn't influence the result.

The scene is here if you need it: https://github.com/rustcycles/rustcycles/blob/master/data/arena/arena.rgs

In editor 14f652ec it shows Forward render path on Floor top, in c24bfa5679161625c7edad07d7df93cb75979522, it shows Deferred. If i switch it to Forward, i get transparency again so it appears to be just a problem with loading the scene.

**Comment by mrDIMAS** [comment]
I checked why this happens and this is just data format change, previously render path was stored as a `render_path: RenderPath`, now it is stored as `render_path: TemplateVariable<RenderPath>`. Visit implementation of TemplateVariable is not smart enough to preserve full backward compatibility. There are lots of hacks to preserve it as much as possible, but it is still limited. So I'd advise you to just re-save your scene with correct render path of Floor, I fixed all known issues that might corrupt scene files so you can re-save it freely.

**Comment by martin-t** [comment]
Thanks, works for me.
