### ISSUE TITLE
Mismatched types: expected `u32`, found `u64` - when installing Fyrox Editor on Raspberry Pi 4

### ISSUE THREAD

**Issue by SamMatzko** [FyroxEngine/Fyrox#299]
When I try to install the Fyrox editor on a Raspberry Pi 4 model B, it downloads everything, and compiles most of the code, but when it starts compiling `rg3d-sound v0.26.0`, I get this error message:

```
error[E0308]: mismatched types
  --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rg3d-sound-0.26.0/src/device/alsa.rs:87:17
   |
87 |                 frame_count as u64,
   |                 ^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
87 |                 (frame_count as u64).try_into().unwrap(),
   |                 +                  +++++++++++++++++++++

error[E0308]: mismatched types
  --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/rg3d-sound-0.26.0/src/device/alsa.rs:94:17
   |
94 |                 &mut exact_size,
   |                 ^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |
   = note:    expected raw pointer `*mut u32`
           found mutable reference `&mut u64`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rg3d-sound` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rusty-editor v0.11.0`, intermediate artifacts can be found at `/tmp/cargo-installteEBSP`

Caused by:
  build failed
```

The command I ran to install it was:

```
cargo install rusty-editor
```

Is this just because the Raspberry Pi is too small to install Fyrox, or is this because there's some dependency that's missing? I'd appreciate any guidance or insight on this.

**Comment by SamMatzko** [comment]
Wait... I've just installed the dependencies, and now I'm installing the editor again. I should have done that before posting the issue, but I can't delete it. I'll let you all know how it goes...

**Comment by Barugon** [comment]
@SamMatzko, can you give [this](https://github.com/Barugon/Fyrox/tree/target_32bit) branch a try? If it works then I'll make a PR.

**Comment by Barugon** [comment]
BTW, is there a reason that you're using a 32bit OS?

**Comment by mrDIMAS** [comment]
Raspberry Pi is not supported at all, just because it does not have OpenGL 3.3 support.
