### ISSUE TITLE
‘Soft particles’ ,Is it possible to simulate flexible effects such as cloth？

### ISSUE THREAD

**Issue by smallverse** [FyroxEngine/Fyrox#307]
Hi,‘Soft particles’ ,Is it possible to simulate flexible effects such as cloth？
like this "[Flex](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/flex/flex.md) or [Cloth actors](https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/flex/cloth.md)"，use NVIDIA PhysX and Flex.

**Comment by mrDIMAS** [comment]
Hi, you can try to emulate that using a grid of ball rigid bodies connected with ball joints. Also you need to "attach" each vertex of your cloth to respective rigid body, so in short - yes it is possible, but there is no built-in solution for that.

**Comment by smallverse** [comment]
ok，thank you~

**Comment by smallverse** [comment]
> Hi, you can try to emulate that using a grid of ball rigid bodies connected with ball joints. Also you need to "attach" each vertex of your cloth to respective rigid body, so in short - yes it is possible, but there is no built-in solution for that.

Hi, my skills are limited,and in your experience if you're going to do that, Which Fyrox apis are used?
