### ISSUE TITLE
Panic when switching Partical System's lifetime from None to Some

### ISSUE THREAD

**Issue by lihe07** [FyroxEngine/Fyrox#309]
When I'm trying to switching a Partical System's lifetime, the editor paniced
This is the detailed output:

```
thread 'main' panicked at 'Attempt to borrow destroyed object at [Idx: 36; Gen: 1] handle.', ...\rg3d-core-0.19.0\src\pool.rs:613:21
```

**Comment by mrDIMAS** [comment]
That's known bug, it happens because editor updates scene and destroys all objects with lifetime < 0.
