### ISSUE TITLE
[Feature Request/Need guidance] Implementing `fyroxed` DPR Scaling

### ISSUE THREAD

**Issue by connorgmeehan** [FyroxEngine/Fyrox#318]
Hi Fyrox team, I've been following the project for a while and am interested in starting my own project.  I was taking a look at the editor and the UI is too small to use.

(It's about 0.75 as large as this in terms of screen space)
<img width="346" alt="Screen Shot 2022-05-23 at 8 24 23 pm" src="https://user-images.githubusercontent.com/7402063/169799513-07299675-ef78-4adb-8331-ad909f99d393.png">

I noticed all of the widths and heights are hardcoded.  How hard would it be to add a DPR settings and share it to all widgets.  I could possibly help implement this with some guidance from a more experienced maintainer. 

I'm keen to get more into rust I work as a creative technologist and studied interaction design and it would be cool to apply these skills to a larger project + these changes could open the the door for improving the UI more in the future.

**Comment by revenkroz** [comment]
Can confirm. I have the same issue. It is too small to use on high DPI screens.

**Comment by mrDIMAS** [comment]
Hello, it is now possible to implement, by adding a simple scaling transform for the root of the UI. I did a quick research if it is possible and it seems it mostly works, but there are some issues with coordinates calculation here and there. For example popups does not center, their positioning does not take scaling into account. So in general if those issues are fixed it will work ok.

**Comment by mrDIMAS** [comment]
@connorgmeehan @revenkroz please check if the editor takes DPI scaling into account for you. It should also apply changes if DPI is changed in runtime, or editor window moved to a monitor with different DPI.

**Comment by mrDIMAS** [comment]
There could be some quirks left, just because some places may use incorrect coordinate system (for example set screen-space coordinates to local-space). Please report any of these, I tried to find all of them, but I use 1.0 screen scaling on daily basis so I simply won't see these unless I explicitly change scaling.

**Comment by mrDIMAS** [comment]
Fixed in 0.27+.
