### ISSUE TITLE
Some PNG files display red areas in part of the image

### ISSUE THREAD

**Issue by 64kramsystem** [FyroxEngine/Fyrox#320]
If I open some images, either via Fyrox (in a game) or in Fyroxed, red areas are displayed as part of the image. Such corruption only displays in Fyrox; other programs/libraries (Eye of MATE, GIMP, Github web interface, the PyGame library) don't have this problem.

This is an example:

![image](https://user-images.githubusercontent.com/1595356/170792319-e27a0822-5acd-4d03-a6ac-fc72d796242a.png)

This is how the image looks when opened on Gimp:

![image](https://user-images.githubusercontent.com/1595356/170792341-fdd515fa-420e-4714-a5d2-c1480bc5d8b3.png)

[This](https://github.com/64kramsystem/rust-game-ports/blob/master/source_projects/soccer/images/s9.png) is a link to the image file.

**Comment by mrDIMAS** [comment]
That's a bug in image compression, you can disable it using 

```rust
 engine
            .resource_manager
            .state()
            .containers_mut()
            .textures
            .set_default_import_options(
                TextureImportOptions::default().with_compression(CompressionOptions::NoCompression),
            );
```

**Comment by 64kramsystem** [comment]
Hello!

I still experience the issue. I've put the command at the very top of `GameState#init`:

```rs
impl GameState for GameGlobal {
    fn init(engine: &mut Engine) -> Self {
        // As of Fyrox v0.26, there's a bug in the images compression.
        // See https://github.com/FyroxEngine/Fyrox/issues/320.
        //
        engine
            .resource_manager
            .state()
            .containers_mut()
            .textures
            .set_default_import_options(
                TextureImportOptions::default().with_compression(CompressionOptions::NoCompression),
            );
```

this runs before any texture is loaded.

I also notice that those images flicker, I don't know if it's related.

**Comment by 64kramsystem** [comment]
If I convert the image(s) to GIF, I don't experience the problem (even without workaround).

**Comment by mrDIMAS** [comment]
Ok, maybe I shouldn't check bugs like this early in the morning 😄 . It could be relate to image loader, it is based on `image` crate. I'll check it.

**Comment by 64kramsystem** [comment]
I'm also having other problems (possibly related) with transparency. This is a sample of how a PNG with multiple levels of transparency renders:

![image](https://user-images.githubusercontent.com/1595356/172061808-e002ace8-b69d-4ca3-b258-ebee3ead2a12.png)

What is black should be transparent, and what is green inside the square, should be much darker.

PNG here: ![players00.png](https://user-images.githubusercontent.com/1595356/172061839-99ad6cbb-e9fb-45fd-91a8-7570be73f257.png)

**Comment by mrDIMAS** [comment]
Some of your images are in `LuminanceAlpha8` format which is interpreted by the engine as `RedGreen8` which results in `R, G, R, G` color when fetching the texture.

**Comment by 64kramsystem** [comment]
> Some of your images are in `LuminanceAlpha8` format which is interpreted by the engine as `RedGreen8` which results in `R, G, R, G` color when fetching the texture.

Is this considered an issue with the engine (I don't have the technical knowledge)? With all the tools i've tried (Firefox, GNOME default image viewer, GIMP, Feh), it displays correctly.

**Comment by 64kramsystem** [comment]
Oh wow. Thanks! :pray:
