### ISSUE TITLE
Add reflection

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#330]
There is a need in a runtime reflection to reduce amount of boilerplate code needed to handle changed properties in the editor. Reflection should support setting a value using its path (like "foo.bar.baz[0].foobar").

**Comment by toyboot4e** [comment]
mrDIMAS on Discord pointed some boilerplate codes:

- Define command for each field:
https://github.com/FyroxEngine/Fyrox/blob/7b2b76f4928b308e8dd2da1efef6e4544da702cf/editor/src/scene/commands/camera.rs#L19

- Handle each property change:
https://github.com/FyroxEngine/Fyrox/blob/7b2b76f4928b308e8dd2da1efef6e4544da702cf/editor/src/inspector/handlers/node/base.rs#L19
