### ISSUE TITLE
Wrong colors when debugging physics

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#331]
`DebugRenderBackend::draw_line` receives color as HSLA but fyrox reads it as RGBA. This results in most lines being white/yellowish.

This doesn't appear documented on the function itself, only [here](https://github.com/dimforge/rapier/blob/master/src/pipeline/debug_render_pipeline/debug_render_style.rs#L5), but rapier's tests/examples treat it as HSLA: https://github.com/dimforge/rapier/blob/master/src_testbed/debug_render.rs#L45

Rapier issue about clarifying the docs: https://github.com/dimforge/rapier/issues/370

**Comment by mrDIMAS** [comment]
Good catch! I'm very surprised that the color is not in RGBA. I'll create Hsl color conversion to bypass this.
