### ISSUE TITLE
As of now, it seems like `fyrox-template` command doesn't work (at least for me).

### ISSUE THREAD

**Issue by StaticESC** [FyroxEngine/Fyrox#332]
Did `cargo install fyrox-template`. Installed `fyrox-template v0.3.0`. Then did `fyrox-template` and got `zsh: command not found: fyrox-template`.

**Comment by DuckEater54** [comment]
Check the ``$user/.cargo/bin/`` folder and check for a fyrox-template executable. List what executables you have in the folder.

**Comment by StaticESC** [comment]
Right. Just did that. I realised that the executable could be in some `/bin` folder not in `$PATH`. Did cargo started doing this recently? (Not putting bins in path?) or am I missing something?

**Comment by DuckEater54** [comment]
> Right. Just did that. I realised that the executable could be in some `/bin` folder not in `$PATH`. Did cargo started doing this recently? (Not putting bins in path?) or am I missing something?

No, cargo does add the .cargo/bin/ folder to the path. When I installed arcolinux one time I had to manually add all the stuff to $PATH.

**Comment by StaticESC** [comment]
Alright, maybe it makes sense as I use endevouros which is also an Arch derivative. Thank you so much!
