### ISSUE TITLE
fyrox-template was installed but cannot be found by bash?

### ISSUE THREAD

**Issue by Ryder17z** [FyroxEngine/Fyrox#336]
I just started taking a look at Fyrox, using https://fyrox-book.github.io/fyrox/beginning/scripting.html and it seems the fyrox-template doesn't install correctly as it will claim to be installed but bash says it cannot be found.

**Comment by mrDIMAS** [comment]
Hello, this issue should help https://github.com/FyroxEngine/Fyrox/issues/332 . In short - check `$user/.cargo/bin/` folder, and add it to the `$PATH`. I'll add this to build instructions.

**Comment by Ryder17z** [comment]
I don't know how to set that up permanently so I just threw together a band-aid helper:

**make_template.sh**
```
#!/bin/bash
echo "adding to $ PATH temporarily"
export PATH=$PATH:/home/ryder/.cargo/bin/
fyrox-template --name platformer
```

Not ideal but it works.

**Comment by mrDIMAS** [comment]
Closing this since book now have a solution for this - https://fyrox-book.github.io/fyrox/beginning/scripting.html#project-generator.
