### ISSUE TITLE
Script assignment in editor fails with: "Failed to set property base.script! Incompatible types!"

### ISSUE THREAD

**Issue by Ne94fets** [FyroxEngine/Fyrox#342]
Hello, 

I recently updated to release version 0.27.0, I also tried 0.27.1 and I am not able to assign scripts to entities. 
Also if I try to swap the `Player` script with `Jumper` in the `example/scripting` I get the same error message:
```
Failed to set property base.script! Incompatible types!
```

I located the error throwing line in `editor/src/comman/universal.rs` line 94, but I could not find the reason why it fails.

**Comment by mrDIMAS** [comment]
Hi, thanks for the report, I'll try to fix it asap. It seems that script property editor is bugged.

**Comment by mrDIMAS** [comment]
The issue is fixed, please confirm that it works for you too.

**Comment by Ne94fets** [comment]
Thank you very much. The script assignment works again. 

Keep up your hard work. This is a great project and I like this engine very much. A cup is on its way! ;)
