### ISSUE TITLE
Got a virus by launching Fyroxed.exe

### ISSUE THREAD

**Issue by Bipbip2109** [FyroxEngine/Fyrox#348]
Windows defender found "Trojan:Win32/Bearfoos.A!ml" in the file and stopped it, idk if it's really a virus but I ain't risking my pc.
Any idea of what happened here ?

**Comment by mrDIMAS** [comment]
Yeah, there are similar false positives for other software, like [this one](https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus). However for me Windows Defender does not trigger the alarm when launching the editor 🤔

**Comment by Bipbip2109** [comment]
Yeah I rebuilded the editor and it doesn't happen anymore. W defender being weird I guess
