### ISSUE TITLE
README.md WebAssembly link throws an 404

### ISSUE THREAD

**Issue by The-Jon** [FyroxEngine/Fyrox#350]
In README.md: 

-> **General** 
-> PC (Windows, Linux, macOS) and [Web (WebAssembly) support](https://fyrox.rs/assets/webexample/index.html) 
=> throws an 404

**Comment by mrDIMAS** [comment]
There are demo projects now - https://fyrox.rs/examples.html and the readme was shorted significantly. Closing this.
