### ISSUE TITLE
Scripts return a DirectlyInheritableEntity Is not satisfied error. 

### ISSUE THREAD

**Issue by BeyondTomrrow** [FyroxEngine/Fyrox#358]
When following along the blog post for 0.27 you will get an ``` impl ScriptTrait for Example {
    |      ^^^^^^^^^^^ the trait `DirectlyInheritableEntity` is not implemented for `Example' ```

This also occurs with ```fyrox-template script --name example``` command to generate the template. 

Is there a current workaround?

**Comment by mrDIMAS** [comment]
This is known and happens when using latest engine and "outdated" tutorials. You can implement the trait using following macro:

```rust
use fyrox::{scene::DirectlyInheritableEntity, impl_directly_inheritable_entity_trait};
...
 impl_directly_inheritable_entity_trait!(YourScript;)
```

**Comment by mrDIMAS** [comment]
Keep in mind, that this trait (and macro) was removed in `inheritance` [branch](https://github.com/FyroxEngine/Fyrox/tree/inheritance). It will be merged to master quite soon.

**Comment by BeyondTomrrow** [comment]
Thank you for the quick response and for the fix.
