### ISSUE TITLE
Editor unusable with trackpad

### ISSUE THREAD

**Issue by blaumeise20** [FyroxEngine/Fyrox#364]
I just started to use Fyrox, but I can't use the editor because every movement I do with my trackpad is way too fast. Is there a setting to change that speed or is it just a bug?

**Comment by mrDIMAS** [comment]
[As discussed in Discord](https://discord.com/channels/756573453561102427/756573453561102430/1021030543070068838), this seems to be OS-related issue. The engine uses `winit` crate to handle input, so maybe it is worth filing an issue on their page (with a minimal repro of course).

**Comment by jhfhngj** [comment]
Use a mouse! If my solution never works, change the speed of mouse speed setting.

**Comment by jhfhngj** [comment]
Use a mouse! If my solution never works, change the speed of mouse speed setting.

**Comment by blaumeise20** [comment]
Well I don't want to use a mouse lol. I use the magic trackpad from Apple.

**Comment by jhfhngj** [comment]
If you don't want to, change the speed of mouse speed setting.

**Comment by blaumeise20** [comment]
That would affect everything else too, which is what I don't want.

**Comment by jhfhngj** [comment]
Use a mouse on a trackpad maybe?
