### ISSUE TITLE
Ability to change editor controls

### ISSUE THREAD

**Issue by InZan123** [FyroxEngine/Fyrox#366]
Since I have previously used Unity and since their Q is down and their E is up, it's a bit weird using this editor since here they are reversed. I think it would be pretty nice to be able to change controls.

**Comment by Tom60chat** [comment]
Same, I don't have a QWERTY keyboard so it's complicated to move the camera of the editor.

**Comment by mrDIMAS** [comment]
Hi, I'll try to add an ability to change editor controls closer to the release of 0.29. It _should_ (™) happen in at the end of December.

**Comment by mrDIMAS** [comment]
It is now possible to change editor controls: 
![изображение](https://user-images.githubusercontent.com/2785135/211085204-08d581bf-6021-4b1f-ac43-54258112316c.png)

**Comment by mrDIMAS** [comment]
@InZan123 @Tom60chat please check the new functionality.

**Comment by Tom60chat** [comment]
Thanks for the update!

**Comment by mrDIMAS** [comment]
Closing this, if you find any problems with this - feel free to reopen.
