### ISSUE TITLE
Question about wasm

### ISSUE THREAD

**Issue by GOVYANSONG** [FyroxEngine/Fyrox#396]
I failed to find a documentation that contains information about feature support on wasm and by extension, proper guidance on either creating a new game or converting a non-wasm one to wasm. I quickly reviewed the wasm example and very much interested in making the navmesh example to run as wasm in web browser. My current understanding is that: majority of work is to add wasm_bindgen and expect it to just work out as expected. Not sure about my naive understanding due to insufficient knowledge of this engine. Please share your thoughts. thanks.

**Comment by mrDIMAS** [comment]
Hi, `wasm_pack` should do all the work for you. Just try to copy `navmesh` example contents to your project and build it with `wasm-pack build --target web`. There's also dedicated WASM example - https://github.com/FyroxEngine/Fyrox/tree/master/examples/wasm. The readme there should also be helpful. If you have some more questions, just ping me.

**Comment by GOVYANSONG** [comment]
thanks for the info. I was able to run the wasm example in browser.
