### ISSUE TITLE
Editor Scene Graph box select and subnode select

### ISSUE THREAD

**Issue by tgerpheide** [FyroxEngine/Fyrox#399]
Maybe these should be 2 different issues, but these would help a lot with productivity. User should be able to use the shift modifier to box select nodes in the scene graph as well as select subnodes of a node like the editor could do in the past (ctrl + down or whatever it was)

**Comment by mrDIMAS** [comment]
You mean click on a node in the World Viewer, hold shift and click on some other node and this should select all the nodes between the first and the last?
