### ISSUE TITLE
wasm error with condvar mutex

### ISSUE THREAD

**Issue by GOVYANSONG** [FyroxEngine/Fyrox#404]
I was able to run my game in editor and wasm_pack generated the wasm file without any issue. but when i run it in browser e.g. Chrome, it threw following errors:

panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/locks/condvar.rs:21:9

panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', library/std/src/sys/wasm/../unsupported/locks/mutex.rs:24:9

**Comment by invokermain** [comment]
I'm running into the same thing, I'm guessing it's something that might be fixed by this bit in the wasm example? https://github.com/invokermain/Fyrox/blob/master/examples/wasm/src/lib.rs#L302

**Comment by GOVYANSONG** [comment]
I have been experimenting with various approaches. following is a working code snippet with tokio. I will run the real game and report further progress:

tokio = {version = "1.21.2", features=["rt"]}

#[wasm_bindgen]
pub fn main_js() {
    set_once();

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    
    rt.block_on(
       async {
            let handle = tokio::runtime::Handle::current();
            let res = handle.spawn(
                say_hello() 
            ).await.unwrap();
            Log::warn(format!("test : {:?}", res + 11));

            let handle = tokio::runtime::Handle::current();
            let res = handle.spawn(
                say_hello() 
            ).await.unwrap();
            Log::warn(format!("test : {:?}", res + 22));
        /*
                    let mut executor = Executor::new();
            executor.add_plugin_constructor(GameConstructor);
            executor.run();
         */

        }
    );
}

async fn say_hello() -> u8 {
    println!("Hello, world!");
    80
}

**Comment by GOVYANSONG** [comment]
Update: SceneLoader::from_file() caused panic with the original error.

**Comment by mrDIMAS** [comment]
So, the issue is that `executor` is using `block_on` method on every platform. It should use `fyrox::core::wasm_bindgen_futures::spawn_local()` instead and wait until the scene is loaded in the main loop. It should be relatively easy to fix. Shame on me: I didn't test executor to run on WASM.

**Comment by mrDIMAS** [comment]
I'll try to fix that today.

**Comment by mrDIMAS** [comment]
So first steps to fix the issue were made. New `AsyncSceneLoader` works fine with WebAssembly, now it is time to improve `fyrox-template` - it needs a separate `executor-wasm` project for WebAssembly. `executor` itself cannot be modified (at least I don't see how to do it), because WebAssembly requires very specific project structure:

- Your game must be a dynamic library
- A bunch of service code (codegen attributes, helper methods to catch and report panic, etc) must be added.

I hope I can add this today, this is interesting task and I'm eager to see some of my games (this one https://github.com/mrDIMAS/FishFolly specifically) working on WebAssembly targets.

**Comment by GOVYANSONG** [comment]
@mrDIMAS , thanks for the quick turnaround and awesome effort. what is the general approach to replace block_on with spawn_local?

**Comment by mrDIMAS** [comment]
`fyrox-template` is now updated and generates `executor-wasm` crate alongside the `executor`. `executor-wasm` contains readme with build instructions. All you need to do is to re-generate project with the `fyrox-template` and follow build instructions in the readme. Also make sure to follow this guide https://fyrox-book.github.io/fyrox/beginning/scripting.html#using-latest-engine-version when trying to use the latest changes.

**Comment by mrDIMAS** [comment]
This is what I have after building `executor-wasm` and running it in Firefox:
![изображение](https://user-images.githubusercontent.com/2785135/202021779-1e69e3ac-db96-4e03-8f5d-ea5ddb9f80fb.png)

**Comment by invokermain** [comment]
I've updated [my learning project](https://github.com/invokermain/man-vs-ball) to use the wasm changes above. It now tries to load!

But it doesn't run 100%, I just get a black screen and the following error messages in the console:
![image](https://user-images.githubusercontent.com/44192816/202034469-1cff6138-b62b-44f6-8465-e08b2f004274.png)

My code doesn't do anything fancy, so I wonder if there is another wasm incompatibility within the library? My guess is something withing my scene that is failing to load?

Also in case it is of note, using the new generated wasm executor file I get quite a few errors/warnings from vscode:

## 1
![image](https://user-images.githubusercontent.com/44192816/202034189-8eb2cc2c-bbf1-4c82-9d4b-7b873ea84b70.png)

## 2
![image](https://user-images.githubusercontent.com/44192816/202034292-1c1b2a59-15c0-4e3b-8073-e9549a28975a.png)

## 3
![image](https://user-images.githubusercontent.com/44192816/202034345-36fe88da-19be-4850-88bf-066fd66d7836.png)

**Comment by GOVYANSONG** [comment]
Try to copy the rgs file from data folder (at root of project) to under executor-wasm e.g. executor-wasm/data/scene.rgs.

**Comment by invokermain** [comment]
> Try to copy the rgs file from data folder (at root of project) to under executor-wasm e.g. executor-wasm/data/scene.rgs. this is in cargo.toml: fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev="23d81ed" }

It's not that unfortunately, data is in there (the unable to load scene error is: `[ERROR]: Unable to load data/scene.rgs override scene! Reason: NotSupportedFormat`), I have just .gitignored it to not duplicate the assets in the repo, and Fyrox is up to date with latest as well.

**Comment by GOVYANSONG** [comment]
Update:

I have modified code to use the new async scene loader. it worked fine inside editor but in browser, fetch_result never returned the scene from model file. At least, i can see a black screen in browser window now.

**Comment by mrDIMAS** [comment]
The issue should be fixed, I got @invokermain 's project running in both Firefox and Chrome:
![изображение](https://user-images.githubusercontent.com/2785135/202212668-6c433558-799a-4afd-aa48-8b2100a4eaef.png)

**Comment by mrDIMAS** [comment]
WebAssembly is kinda annoying, the fact that you cannot block to execute a future is sad. However, there's one good thing about this - having non-blocking code will make your app much better from user perspective. You can draw a progress bar, or some other stuff while game's assets are loading.

**Comment by mrDIMAS** [comment]
@invokermain If you have any improvements to `executor-wasm` template, please make a PR  🙏

**Comment by GOVYANSONG** [comment]
Finally, i was able to get scene and model all loaded and rendered in browser. cheers to all. but now, I cannot exit the game by setting *control_flow = ControlFlow::Exit in update method of plugin trait of game. Any thought?

**Comment by GOVYANSONG** [comment]
original issue is resolved
