### ISSUE TITLE
Terrain brush being odd on on touched air

### ISSUE THREAD

**Issue by DuckEater54** [FyroxEngine/Fyrox#417]
So I had zoomed out, to move around and I zoomed in to this new area to check where I was in case of readjustment needed. I noticed a green thing on my screen, looked close and saw the words of chrome behind it.

This was on a brand new scene and project, immediately ran editor after generating and building the projects initially.

Shape: circle
Radius: 4.000
Mode: modify height map
Amount: 4.000

Ubuntu 22.04.1 LTS
Fyrox-template 0.5.1
Gnome 42.5

Edit: It doesn't show the window behind it in Green on Skybox, it shows the green tinted window on the terrain itself, and I believe the reason why it looks like the skybox on the video is because I was looking at it from the other side perhaps. I am not sure. It will ONLY show on the green, in the brush it appears

My terrain node is default size, position and rotation, Static, within a Rigid body alongside a Collider

**Comment by DuckEater54** [comment]
https://user-images.githubusercontent.com/86613052/209815614-80869949-5664-4d0e-8283-f830ad5fa066.mp4

**Comment by mrDIMAS** [comment]
Cannot reproduce.
