### ISSUE TITLE
Is there any demo for wasm?

### ISSUE THREAD

**Issue by otabekgb** [FyroxEngine/Fyrox#418]
Is there any demo for wasm?

**Comment by Neugierdsnase** [comment]
I'm also curious about this.

**Comment by mpwsh** [comment]
Maybe https://github.com/FyroxEngine/Fyrox/tree/master/examples/wasm ?

**Comment by otabekgb** [comment]
Thanks, that worked

> Maybe https://github.com/FyroxEngine/Fyrox/tree/master/examples/wasm ?

**Comment by mrDIMAS** [comment]
Actually, you should follow [this instructions](https://fyrox-book.github.io/fyrox/beginning/scripting.html) and in generated project's folder navigate to `executor-wasm` and follow docs in `README.md` there.
