### ISSUE TITLE
[editor][bug] When editor started from console of vs code, editor works very slow and project runs very slow

### ISSUE THREAD

**Issue by stalker57241** [FyroxEngine/Fyrox#424]
When I'm first time heard about this project and successfully created first project, I'm used console of vs code for starting editor. Unfortunately, output to console of vscode is **very** slow.

I'm found if use

```
start cargo run --package editor --release
```

It started in moments.

What about changing editor and executor(I think problem will be same) startup for fixing this problem?

**Comment by mrDIMAS** [comment]
I'm confused, what are you trying to do? If you need performant editor, then of course, you should build the editor in release mode. The same rule applies to your game (executor).

**Comment by stalker57241** [comment]
...First launch and not installed dependencies. How I can forget about this?! Sorry for distracting you
