### ISSUE TITLE
wasm_bindgen not found in core

### ISSUE THREAD

**Issue by nuked44** [FyroxEngine/Fyrox#431]
rust-analyzer gives me the error:

```
failed to resolve: could not find `wasm_bindgen` in `core`
could not find `wasm_bindgen` in `core`
```
in executor-wasm/src/lib.rs: [ln 4 col 18]
and following uses on new template

wasm32-unknown-unknown and wasm-pack are both installed as per README.md in executor-wasm

**Comment by mrDIMAS** [comment]
Is everything compiles? If so, then it is just `rust-analyzer` issue.

**Comment by nuked44** [comment]
Is there anything dependent on the wasm executor or is it safe to just delete the folder and remove it from the workspace members?

**Comment by mrDIMAS** [comment]
You can delete it if you don't need it.
