### ISSUE TITLE
Fyrox Editor Taskbar Icon

### ISSUE THREAD

**Issue by MasteryOfMastering** [FyroxEngine/Fyrox#441]
Currently, when you launch the game engine, the default icon is used (depending on OS), which makes it difficult to quickly switch between the engine and other applications. Adding a taskbar icon of the game logo would help immensely!

**Comment by mrDIMAS** [comment]
I guess, the easiest way would be to use `engine.graphics_context.as_initialized_mut().window.set_icon(image)`, where `image` - fyrox icon in RGBA8 format. See docs for `set_icon` for details.

**Comment by mrDIMAS** [comment]
Fixed in https://github.com/FyroxEngine/Fyrox/commit/26b38abe297d90898ab4cce9a30dc62e6d3ca32e
