### ISSUE TITLE
TextBox input duplicated

### ISSUE THREAD

**Issue by martin-t** [FyroxEngine/Fyrox#505]
Steps to repro:
- `cargo run --example textbox`
- Type into the TextBox
- Every letter will appear twice with a short delay

I believe this started happening after the recent update to 0.29.0-beta.0

**Comment by mrDIMAS** [comment]
On which OS you're? I'm on Windows and it works fine: 
![textbox](https://github.com/FyroxEngine/Fyrox/assets/2785135/97dbe80e-a80f-4667-84c3-91c2e6e54f58)

**Comment by martin-t** [comment]
Kubuntu 22.04

**Comment by martin-t** [comment]
Also confirming it started happening on f2ce4fb872804d5299bed01b2a9fad0f1b24077c as suspected

**Comment by mrDIMAS** [comment]
I did a potential fix, could you please re-check?
