### ISSUE TITLE
Incorrectly imported .fbx model

### ISSUE THREAD

**Issue by egsam98** [FyroxEngine/Fyrox#515]
Hello, I tried many times to import some Blender model and run animation but I don't see any mesh in model displayed:
![image](https://github.com/FyroxEngine/Fyrox/assets/38672780/cc9c57c4-c916-4c38-9e06-b852707e07e0)
Those dots on screenshot are selected skeleton nodes.

Noticed it happens due to with skeleton/armature: if I exclude armature from .fbx I see all meshes as it should be. Checked this model on different engines like Unity and Godot, both of them show my model and play animation correctly. Unfortunately, I don't understand the reason of this broken import in Fyrox, need some help or hints. Thanks.

Link to .fbx:
https://drive.google.com/file/d/1cbTtW1LVqlYzlkAgHtvZtESd0j27QRYu/view?usp=sharing

**Comment by mrDIMAS** [comment]
Hi, it is hard to tell why this happens. Meanwhile it seems that it can be fixed by re-exporting: 

![изображение](https://github.com/FyroxEngine/Fyrox/assets/2785135/6226bee0-eed7-47c4-b716-44c99468e53c)

I'll try to find out why it happens.

**Comment by egsam98** [comment]
Tried the same steps, i.e. to create new project and download .fbx from that link:
![image](https://github.com/FyroxEngine/Fyrox/assets/38672780/7367ea6e-6d7c-4f99-91be-2e324122bd9e)
It's strange.

**Comment by mrDIMAS** [comment]
I re-exported your FBX from 3ds max and loaded it back in the editor and works fine, even animations are playing. When doing the same in Blender, it works only partially - only some parts of the model are visible which is very odd. Also, both Blender and 3ds max having issues loading your FBX, it takes about a minute to import/export it.

**Comment by egsam98** [comment]
Right now I re-exported my model too. It works as expected in Blender. But when I try to add it to new empty scene it retain invisible. Would you like to share me your blender export options?
![image](https://github.com/FyroxEngine/Fyrox/assets/38672780/901f20d4-0cb6-401e-9d35-814bbf5cb638)
In the right corner

**Comment by mrDIMAS** [comment]
I used default export options. However it still works _partially_, the model looks incorrect. 

However, if I use 3ds max exporter - it works fine. Here's the re-exported model from **3ds max**: https://drive.google.com/file/d/11A3KahpgWqvxdfR1z8z12dK69T1HlADT/view?usp=sharing

**Comment by mrDIMAS** [comment]
By the looks of it, the model looks very complex with a lot of "moving parts" and it is hard to tell what causing these issues. Does it have blend shapes btw?

**Comment by egsam98** [comment]
![image](https://github.com/FyroxEngine/Fyrox/assets/38672780/1d9558d4-2962-453b-b21e-8c76ba8ed841)
Confirming that it's really working after your export from 3ds. No, it doesn't have because I imported this model as warcraft3 model .mdx using third-party python scripts.
I think we can close this issue because the problem starts concerning more 3D-modelling area. But still seems strange how Unity, Godot could normally import my model.... Nevertheless, thank you for help, I consider using 3ds max then :) 

Btw, best Rust game engine I've ever tried (including godot bindings)
