### ISSUE TITLE
Selecting and Deselecting Objects Cause Memory Increasing (Leaking?)

### ISSUE THREAD

**Issue by IceGuye** [FyroxEngine/Fyrox#559]
There are a few occasions which may cause memory increasing (or leaking?), such as selecting and deselecting objects.

System: Feodra Linux 38 with Gnome X11.
Version: Newest git master.
Reproduce:
1) Use fyrox-template to create a brand new 3D project.
2) Change the cargo.toml to the git master.
3) Start the editor with `cargo run --package editor --release`.
4) Select and deselect some object, such as the default cude, light, and camera.
5) Check the system monitor to see the memory increasing.

See the video for details.

https://github.com/FyroxEngine/Fyrox/assets/7291463/7b8636d1-48b1-4a03-bc7c-ea1fb0972f87

**Comment by mrDIMAS** [comment]
~~Works on my PC~~ I can't reproduce this on Windows, I selected and deselected various objects dozens of time and memory usage was increased on just 1 Mb. Which is expected, because selection/deselection creates a bunch of commands.

**Comment by LordCocoNut** [comment]
I think this issue could be closed, according to [discord conv](https://discord.com/channels/756573453561102427/941678932791529523/1178054198361870387)
