### ISSUE TITLE
Editor crashes on new project

### ISSUE THREAD

**Issue by Barugon** [FyroxEngine/Fyrox#561]
Create a new project:
```sh
fyrox-template init --name crash --style 3d
```

Run the editor:
```sh
cd crash
cargo run --package executor --release
```

Editor crashes after a few seconds:
```
thread 'main' panicked at /home/barugon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyroxed_base-0.19.0/src/lib.rs:2612:14:
called `Result::unwrap()` on an `Err` value: ExitFailure(1)
```

Fyrox: v0.32.1
Fedora Linux: 38
GNOME Version: 44.6
Windowing System: Wayland
Kernel Version: 6.5.9
Graphics: AMD Radeon RX 6700 XT

**Comment by mrDIMAS** [comment]
Same as #558, it is Wayland-related issue, which comes from `winit`. You could try changing to X11 to bypass the issue.
