### ISSUE TITLE
Can't start "Quick Start" from Fyrox Game Engine Book, I get error: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by kislenko-artem** [FyroxEngine/Fyrox#581]
![2024-01-03_09-5509-55-57](https://github.com/FyroxEngine/Fyrox/assets/13413164/19941bc5-8a06-4f25-b6aa-8a35b26a9df4)

My OS: Ubuntu 22.04
Windowing System: X11
Compiler version: rustc 1.70.0

**Comment by kislenko-artem** [comment]
I used this file, and now it's work. Before this action, my file was looked  as:

![2024-01-03_10-5810-58-37](https://github.com/FyroxEngine/Fyrox/assets/13413164/4dabe872-dfa1-4844-a928-1afff2f854ff)

**Comment by mrDIMAS** [comment]
Hi! It is strange, because CI was successful in the similar environment that you have. Did you try running `cargo update`, may be it will fix the issue? Also, minimum supported Rust version is 1.72.

**Comment by kislenko-artem** [comment]
Thank you for answer.
I cleaned everything and reinstall. Now it is working. I don't know, what it was.
