### ISSUE TITLE
Add an ability to rotate the editor camera using scene gizmo

### ISSUE THREAD

**Issue by mrDIMAS** [FyroxEngine/Fyrox#586]
Add an ability to rotate the editor camera using scene gizmo:

![scene gizmo](https://github.com/FyroxEngine/Fyrox/assets/2785135/4fd16084-775a-45e1-b24a-27c4ece1e845)

Rotation should happen if a user clicks on the gizmo and starts dragging the mouse while holding the button. Ordinary clicks should switch views as before. Scene gizmo is located in `editor/src/scene_viewer/gizmo.rs`

**Comment by Fedron** [comment]
I would like to take this one on if possible?

**Comment by mrDIMAS** [comment]
Hi, yeah, this issue seems to be quite easy to fix, so you can try it.
