### ISSUE TITLE
Editor crash when saving terrain

### ISSUE THREAD

**Issue by DimitriTimoz** [FyroxEngine/Fyrox#598]
When I save or compile the scene which contains a terrain the process doesn't respond.
My environement:
```
fryroxed = "0.20.0" 
fyrox = "0.33.0"
Tested OS: Macos or Ubuntu
```
I tried a new project and the problem is still there.
Lastest logs:
`[INFO]: Settings were successfully saved!`

The building game logs are empty.

**Comment by mrDIMAS** [comment]
Fixed. Run `cargo update` to update the engine. I released 0.33.1 version.
