### ISSUE TITLE
Mixamo mesh import issue

### ISSUE THREAD

**Issue by CategoryOfJessica** [FyroxEngine/Fyrox#608]
Issue:
The corner of a triangle from a standard mixamo model doesn't import correctly.
<img width="1157" alt="Screenshot 2024-02-16 at 10 25 54 AM" src="https://github.com/FyroxEngine/Fyrox/assets/1100484/a2f9ba0b-097a-4641-91fe-7a70b4b60b7d">

How to reproduce:
using fyrox https://github.com/FyroxEngine/Fyrox?branch=master#beb94b817bc073b52342ee666246f073c9254d56
import https://www.mixamo.com/#/?page=1&query=arissa&type=Character

I inspected the model in blender as a sanity check and there wasn't anything peculiar with the UV or vertices.

**Comment by mrDIMAS** [comment]
Hi, the issue should be fixed. Could you please confirm?

**Comment by CategoryOfJessica** [comment]
Yes! It was fixed after cargo update.
