### ISSUE TITLE
Bug found - Clicking in asset browser deleted some files and duplicated the data folder 180+ times until I Ctrl+C the editor process.

### ISSUE THREAD

**Issue by Andy-Olshanky** [FyroxEngine/Fyrox#614]
I was trying to drag n drop an asset into the game editor, and I clicked on the asset browser root (.) folder, then clicked on the data folder. This caused the editor to freeze and become unresponsive, and after a few seconds I look at the terminal and see it typing a bunch of stuff, namely saying "/data/data/data/data...." over and over again, presumably making a new directory or something. When I look in my files, I see one of the folders (called character) in the data folder got deleted, and another data folder was created inside the root data folder. The other folder (called tiles) that was in the initial asset directory got moved into the newly created data folder, but it got it's contents wiped. Opening the new data folder revealed another data folder and tiles folder, but the tiles folder was empty. Clicking on the next level of data folder revealed another data and tiles folder, and I assume this continues on for another 180+ iterations. The data in the tiles folder was still there, in what I assume to be the last level. I have no idea why this happened but I figured I should report this. Thankfully I had like 2 pictures in there of which I had backups, but I'd hate to see this happen to someone with a lot of data to lose sometime in the future.

**Comment by mrDIMAS** [comment]
Hi! Could you please re-check if this bug still occurs on the latest engine?
