### ISSUE TITLE
could this support 3d format like pmx and vmd motion format?

### ISSUE THREAD

**Issue by Tom-Jim** [FyroxEngine/Fyrox#652]
or it have a translation that translate it to fbx or dae,glb etc like assimp in C++ do.or even have a general bundle in engine to translate all 3d formats to union format automatically.it's so damn to import 3d assets from different formats and waste a lot time to translate them from one to another. i think it could make engine have a unique character in game engine like blender in animation.

**Comment by mrDIMAS** [comment]
It could if you write it 😉
