### ISSUE TITLE
Upgrading the version to nightly causes infinite reloading

### ISSUE THREAD

**Issue by YourKindAlly** [FyroxEngine/Fyrox#665]
I use RustRover as my IDE and run all my commands from there. When I input `fyrox-template upgrade --version=nightly` into the console it attempts to reload the cargo, but it doesn't show progress and runs indefinitely. This also causes the project to be unusable as it keeps reloading after restart as well.

![image](https://github.com/FyroxEngine/Fyrox/assets/151460557/635fb5a0-be7d-4a42-ac74-79f184b58eb2)

**Comment by YourKindAlly** [comment]
I also tried `fyrox-template upgrade --version nightly` which didn't work either.

![image](https://github.com/FyroxEngine/Fyrox/assets/151460557/400240f4-e566-4d3c-8dfe-b2c91c798510)

**Comment by mrDIMAS** [comment]
Unrelated to the engine, closing.
